version: '3'
services:
  db:
    image: postgres:10.5-alpine
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: apotek
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    environment:
      ADMINER_PLUGINS: 'dump-json'
volumes:
  dbdata:
