{"cache-control":"no-cache","postman-token":"c7bacf34-f348-44c3-bd4c-d1d4560bd6b6","authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiaWQiOjExLCJlbWFpbCI6ImFkbWluQGdyb3Npcm9iYXQuY29tIn0sImlhdCI6MTU0MDA5NTQzNiwiZXhwIjoxNTQwNzAwMjM2fQ.I3rfxsRySnboIHJmVA-RP1UwrXTB4YBgvwu8ryDnJJA","user-agent":"PostmanRuntime/7.3.0","accept":"*/*","host":"localhost:5000","accept-encoding":"gzip, deflate","connection":"keep-alive","level":"error","message":"Request headers:"}
{"level":"error","message":"Request parameters:"}
{"level":"error","message":"Request body:"}
{"message":"error: column \"products.id\" must appear in the GROUP BY clause or be used in an aggregate function\n    at Connection.parseE (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","level":"error"}
{"cache-control":"no-cache","postman-token":"9ef50b50-d808-4ce2-845b-0a3cad2db3c2","authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiaWQiOjExLCJlbWFpbCI6ImFkbWluQGdyb3Npcm9iYXQuY29tIn0sImlhdCI6MTU0MDA5NTQzNiwiZXhwIjoxNTQwNzAwMjM2fQ.I3rfxsRySnboIHJmVA-RP1UwrXTB4YBgvwu8ryDnJJA","user-agent":"PostmanRuntime/7.3.0","accept":"*/*","host":"localhost:5000","accept-encoding":"gzip, deflate","connection":"keep-alive","level":"error","message":"Request headers:"}
{"level":"error","message":"Request parameters:"}
{"level":"error","message":"Request body:"}
{"message":"error: column \"products.id\" must appear in the GROUP BY clause or be used in an aggregate function\n    at Connection.parseE (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","level":"error"}
{"cache-control":"no-cache","postman-token":"170a42bb-e5ba-496d-b139-f46adc2867ad","authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiaWQiOjExLCJlbWFpbCI6ImFkbWluQGdyb3Npcm9iYXQuY29tIn0sImlhdCI6MTU0MDA5NTQzNiwiZXhwIjoxNTQwNzAwMjM2fQ.I3rfxsRySnboIHJmVA-RP1UwrXTB4YBgvwu8ryDnJJA","user-agent":"PostmanRuntime/7.3.0","accept":"*/*","host":"localhost:5000","accept-encoding":"gzip, deflate","connection":"keep-alive","level":"error","message":"Request headers:"}
{"level":"error","message":"Request parameters:"}
{"level":"error","message":"Request body:"}
{"message":"error: column \"products.id\" must appear in the GROUP BY clause or be used in an aggregate function\n    at Connection.parseE (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","level":"error"}
{"cache-control":"no-cache","postman-token":"1d607e6c-cc2e-4e55-842c-f7118a1c073a","authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiaWQiOjExLCJlbWFpbCI6ImFkbWluQGdyb3Npcm9iYXQuY29tIn0sImlhdCI6MTU0MDA5NTQzNiwiZXhwIjoxNTQwNzAwMjM2fQ.I3rfxsRySnboIHJmVA-RP1UwrXTB4YBgvwu8ryDnJJA","user-agent":"PostmanRuntime/7.3.0","accept":"*/*","host":"localhost:5000","accept-encoding":"gzip, deflate","connection":"keep-alive","level":"error","message":"Request headers:"}
{"level":"error","message":"Request parameters:"}
{"level":"error","message":"Request body:"}
{"message":"error: column \"products.created_at\" must appear in the GROUP BY clause or be used in an aggregate function\n    at Connection.parseE (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","level":"error"}
{"cache-control":"no-cache","postman-token":"19bd091c-4525-443c-be96-3c47c4ff84d0","authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiaWQiOjExLCJlbWFpbCI6ImFkbWluQGdyb3Npcm9iYXQuY29tIn0sImlhdCI6MTU0MDA5NTQzNiwiZXhwIjoxNTQwNzAwMjM2fQ.I3rfxsRySnboIHJmVA-RP1UwrXTB4YBgvwu8ryDnJJA","user-agent":"PostmanRuntime/7.3.0","accept":"*/*","host":"localhost:5000","accept-encoding":"gzip, deflate","connection":"keep-alive","level":"error","message":"Request headers:"}
{"level":"error","message":"Request parameters:"}
{"level":"error","message":"Request body:"}
{"message":"error: column \"products.created_at\" must appear in the GROUP BY clause or be used in an aggregate function\n    at Connection.parseE (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","level":"error"}
{"cache-control":"no-cache","postman-token":"de5213c0-2729-48b3-9baa-2780cc3145dd","authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiaWQiOjExLCJlbWFpbCI6ImFkbWluQGdyb3Npcm9iYXQuY29tIn0sImlhdCI6MTU0MDA5NTQzNiwiZXhwIjoxNTQwNzAwMjM2fQ.I3rfxsRySnboIHJmVA-RP1UwrXTB4YBgvwu8ryDnJJA","user-agent":"PostmanRuntime/7.3.0","accept":"*/*","host":"localhost:5000","accept-encoding":"gzip, deflate","connection":"keep-alive","level":"error","message":"Request headers:"}
{"level":"error","message":"Request parameters:"}
{"level":"error","message":"Request body:"}
{"message":"error: column \"products.id\" must appear in the GROUP BY clause or be used in an aggregate function\n    at Connection.parseE (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","level":"error"}
{"cache-control":"no-cache","postman-token":"af5d3f88-9c19-4ab4-a49b-47c5270941df","authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiaWQiOjExLCJlbWFpbCI6ImFkbWluQGdyb3Npcm9iYXQuY29tIn0sImlhdCI6MTU0MDA5NTQzNiwiZXhwIjoxNTQwNzAwMjM2fQ.I3rfxsRySnboIHJmVA-RP1UwrXTB4YBgvwu8ryDnJJA","user-agent":"PostmanRuntime/7.3.0","accept":"*/*","host":"localhost:5000","accept-encoding":"gzip, deflate","connection":"keep-alive","level":"error","message":"Request headers:"}
{"level":"error","message":"Request parameters:"}
{"level":"error","message":"Request body:"}
{"message":"error: SELECT * with no tables specified is not valid\n    at Connection.parseE (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","level":"error"}
{"cache-control":"no-cache","postman-token":"4b3cab0e-5fef-4060-adfb-fe599dcba271","authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiaWQiOjExLCJlbWFpbCI6ImFkbWluQGdyb3Npcm9iYXQuY29tIn0sImlhdCI6MTU0MDA5NTQzNiwiZXhwIjoxNTQwNzAwMjM2fQ.I3rfxsRySnboIHJmVA-RP1UwrXTB4YBgvwu8ryDnJJA","user-agent":"PostmanRuntime/7.3.0","accept":"*/*","host":"localhost:5000","accept-encoding":"gzip, deflate","connection":"keep-alive","level":"error","message":"Request headers:"}
{"level":"error","message":"Request parameters:"}
{"level":"error","message":"Request body:"}
{"message":"error: column reference \"deleted_at\" is ambiguous\n    at Connection.parseE (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:554:11)\n    at Connection.parseMessage (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:379:19)\n    at Socket.<anonymous> (/Users/jimboy/Sites/grosirobatjs/backend/node_modules/pg/lib/connection.js:119:22)\n    at Socket.emit (events.js:182:13)\n    at addChunk (_stream_readable.js:283:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","level":"error"}
